name: Duckdb_installer

on:
  # Defining workflow_call means that this workflow can be called from
  # your main workflow job
  workflow_call:

jobs:
  duckdb:
    runs-on: ubuntu-latest
    # This is optional; it exposes the plan to your job as an environment variable
    env:
      DUCKDB_LIB_DIR: ${{ inputs.plan }}
    steps:
      - name: Install duckdb
        shell: bash
        run: |
          if ! command -v unzip &> /dev/null; then
            apt-get update && apt-get install -y unzip
          fi

          wget "https://github.com/duckdb/duckdb/releases/download/v1.0.0/libduckdb-linux-amd64.zip"
          mkdir duckdb_lib
          unzip libduckdb-linux-amd64.zip -d duckdb_lib
          echo "DUCKDB_LIB_DIR=$(pwd)/duckdb_lib" >> $GITHUB_ENV
          echo $DUCKDB_LIB_DIR
          ls duckdb_lib